[project]
name = "narrow_hh_backend"
version = "0.1.0"
description = "Backend FastAPI service for job filtering"
authors = [{ name = "kryak", email = "narrow_hh-feedback@mail.ru" }]
requires-python = ">=3.12"
dependencies = [
    "alembic>=1.16.3",
    "asyncpg>=0.30.0",
    "fastapi[standard]>=0.116.0",
    "httpx>=0.28.1",
    "pydantic>=2.11.7",
    "pydantic-settings>=2.10.1",
    "pyjwt>=2.10.1",
    "python-dotenv>=1.1.1",
    "redis>=6.2.0",
    "sqlalchemy>=2.0.41",
    "uvicorn[standard]>=0.35.0",
]

[dependency-groups]
dev = [
    "black>=25.1.0",
    "faker>=37.4.2",
    "mypy>=1.16.1",
    "pytest>=8.4.1",
    "pytest-asyncio>=1.0.0",
    "pytest-cov>=6.2.1",
    "ruff>=0.12.2",
    "testcontainers>=4.12.0",
]

[tool.ruff]
line-length = 100
fix = true
exclude = [
    "src/app/migrations/",
    "src/app/infrastracture/database/migrations.py",
]


[tool.black]
line-length = 100

[tool.mypy]
python_version = "3.12"
strict = true
exclude = [
   "src/app/migrations/",
   "src/app/infrastracture/database/migrations.py",
]


[tool.pytest.ini_options]
pythonpath = [
    ".",
]
asyncio_mode = "auto"
