"""UserToken new field (token_type)

Revision ID: 297911aecadf
Revises: 1e262ad6749e
Create Date: 2025-07-11 20:46:47.706649

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '297911aecadf'
down_revision: Union[str, Sequence[str], None] = '1e262ad6749e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_tokens', sa.Column('token_type', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_tokens', 'token_type')
    # ### end Alembic commands ###
