"""Init create tables

Revision ID: ceab0a0bcc5a
Revises: 
Create Date: 2025-07-13 20:35:06.136063

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ceab0a0bcc5a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_table('head_hunter_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hh_user_id', sa.String(), nullable=False),
    sa.Column('token_type', sa.String(), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=False),
    sa.Column('expires_in', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_head_hunter_tokens_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_head_hunter_tokens')),
    sa.UniqueConstraint('user_id', name=op.f('uq_head_hunter_tokens_user_id'))
    )
    op.create_table('telegram_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_telegram_accounts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_telegram_accounts')),
    sa.UniqueConstraint('telegram_id', name=op.f('uq_telegram_accounts_telegram_id')),
    sa.UniqueConstraint('user_id', name=op.f('uq_telegram_accounts_user_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('telegram_accounts')
    op.drop_table('head_hunter_tokens')
    op.drop_table('users')
    # ### end Alembic commands ###
